name: $(GitVersion.FullSemVer)
pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: Release

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
      - docs/*
      - README.md

steps:
  - task: gitversion/setup@0
    displayName: Install GitVersion
    inputs:
      versionSpec: '5.x'
  - task: gitversion/execute@0
    displayName: Determine Version      

  - script: dotnet pack ./src/XMLDoc2Markdown/XMLDoc2Markdown.csproj -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/out -p:Version=$(GitVersion.SemVer)
    displayName: 'dotnet pack'

  - publish: $(Build.ArtifactStagingDirectory)/out
    artifact: out
    displayName: 'Publish artifact'
